[package]
name = "wasmgame-macros"
version = "0.1.0"
authors = ["Folke Behrens <folke@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
obj = "0.10.1"
quote = "1.0.7"
syn = "1.0.43"
