[package]
name = "wasmgame-macros"
version = "0.1.0"
authors = ["Folke Behrens <folke@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
obj-rs = "0.6.2"
syn = "1.0.42"
quote = "1.0.7"
