[package]
name = "wasmgame-macros"
version = "0.2.0"
authors = ["Folke Behrens <folke@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
obj = "0.10.2"
quote = "1.0.15"
syn = "1.0.86"
