name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up
      run: |
        cargo --version
        rustc --version
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: |
        cargo build --target=wasm32-unknown-unknown --verbose
    - name: Test
      run: |
        cargo test --target=wasm32-unknown-unknown --verbose
